In [1]:
import pandas as pd
import csv

### OLD DRUGS DICT (from website)

In [44]:
df_old_drugs = pd.read_excel("../../Data/drugs/old_drug_names_final.xlsx")
df_old_drugs['record_no'] = 'od' + df_old_drugs['record_no'].astype(str)
df_old_drugs = df_old_drugs.drop(columns=['Unnamed: 0'])
df_old_drugs.head()

  record_no         drug_name     search_string   drug_name_lower
0       od1  abacavir sulfate  abacavir sulfate  abacavir sulfate
1       od1           1592U89           1592u89           1592u89
2       od1   1592U89 sulfate   1592u89 sulfate   1592u89 sulfate
3       od1          Abacavir          abacavir          abacavir
4       od1               ABC               abc               abc

In [45]:
len(df_old_drugs)

62120

### NEW DRUGS DICT

In [4]:
df_new_drugs = pd.read_excel('../../Data/drugs/new_drug_names_final.xlsx')
df_new_drugs = df_new_drugs.drop(columns=['Unnamed: 0'])
df_new_drugs.head()

,record_no,drug_name,search_string,drug_name_lower
0,13067,(+)-calanolide A,calanolide a,(+)-calanolide a
1,13067,calanolide A,calanolide a,calanolide a
2,31334,(+)-enantiomer of DOV 216303,enantiomer of dov 216303,(+)-enantiomer of dov 216303
3,31334,amitifadine (pINN),amitifadine,amitifadine (pinn)
4,31334,amitifadine (USAN),amitifadine,amitifadine (usan)

In [5]:
len(df_new_drugs)

16197

In [17]:
df_old_drugs[df_old_drugs.drug_name == "Condition"]

       record_no  drug_name drug_name_lower
14444        563  Condition       condition
14557        564  Condition       condition
58512       2216  Condition       condition

# TEST

In [6]:
df_new_drugs = df_new_drugs.assign(new_in_old_drugs=df_new_drugs.search_string.isin(df_old_drugs.drug_name).astype(int))
df_new_drugs.head()

,record_no,drug_name,search_string,drug_name_lower,new_in_old_drugs
0,13067,(+)-calanolide A,calanolide a,(+)-calanolide a,0
1,13067,calanolide A,calanolide a,calanolide a,0
2,31334,(+)-enantiomer of DOV 216303,enantiomer of dov 216303,(+)-enantiomer of dov 216303,0
3,31334,amitifadine (pINN),amitifadine,amitifadine (pinn),0
4,31334,amitifadine (USAN),amitifadine,amitifadine (usan),0

In [7]:
len(df_new_drugs[df_new_drugs.new_in_old_drugs==1])

2268

In [8]:
# Duplicates in old drugs dict
df_dup_old_drugs = df_old_drugs[df_old_drugs.duplicated(['drug_name_lower'])]
len(df_dup_old_drugs)

31151

In [9]:
df_dup_old_drugs.head()

     record_no              drug_name        drug_name_lower
499         19                aci-jel                aci-jel
500         19               Acetasol               acetasol
501         19            Acetic acid            acetic acid
502         19  Acetic acid (natural)  acetic acid (natural)
503         19   Acetic acid, glacial   acetic acid, glacial

In [46]:
df_no_dup_old_drugs = df_old_drugs.drop_duplicates(subset='drug_name_lower') 
len(df_no_dup_old_drugs)

30969

In [47]:
df_no_dup_old_drugs.to_excel("../../Data/drugs/old_drug_names_final_no_duplicates.xlsx")

In [10]:
df_dup_old_drugs.groupby(['record_no']).count()

           drug_name  drug_name_lower
record_no
19                39               39
34                12               12
45                27               27
51                14               14
62                17               17
65                34               34
67                 9                9
81                 6                6
99                12               12
101               48               48
108               26               26
110               13               13
113                3                3
121               79               79
129               82               82
138                1                1
143               91               91
159               14               14
172               12               12
173               15               15
180               33               33
181               33               33
189               15               15
199                1                1
205                2                2
216                6                6
222               29               29
224               27               27
225               41               41
226               62               62
...              ...              ...
2342              24               24
2343              20               20
2344               9                9
2345               9                9
2346               9                9
2347               5                5
2348               8                8
2349              18               18
2350               1                1
2353              23               23
2355              38               38
2356              14               14
2358              12               12
2359              26               26
2360              26               26
2361              10               10
2362              10               10
2363              19               19
2365              15               15
2366              14               14
2368               7                7
2370              18               18
2371              11               11
2372              45               45
2374              10               10
2376              83               83
2378              16               16
2379               1                1
2380               3                3
2382               8                8

[1091 rows x 2 columns]

# TEST

In [11]:
df_old_drugs_sample = df_old_drugs[1344:4000]
len(df_old_drugs_sample)

2656

In [12]:
df_old_drugs_sample.head()

      record_no                 drug_name           drug_name_lower
1344         58                   agrylin                   agrylin
1345         58                   Agrelin                   agrelin
1346         58    Anagrelid hydrochlorid    anagrelid hydrochlorid
1347         58            Anagrelide HCl            anagrelide hcl
1348         58  Anagrelide hydrochloride  anagrelide hydrochloride

In [15]:
df_old_drugs_sample[df_old_drugs_sample.duplicated(['drug_name_lower'])]

,record_no,drug_name,drug_name_lower
1430,62,albenza,albenza
1431,62,Albendazol,albendazol
1432,62,Albendazol [INN-Spanish],albendazol [inn-spanish]
1433,62,Albendazole,albendazole
1434,62,Albendazolum,albendazolum
1435,62,Albendazolum [INN-Latin],albendazolum [inn-latin]
1436,62,Bilutac,bilutac
1437,62,EINECS 259-414-7,einecs 259-414-7
1438,62,Eskazole,eskazole
1439,62,HSDB 7444,hsdb 7444
1440,62,NSC 220008,nsc 220008
1441,62,Proftril,proftril
1442,62,SK&F 62979,sk&f 62979
1443,62,SKF 62979,skf 62979
1444,62,UNII-F4216019LN,unii-f4216019ln
1445,62,Valbazen,valbazen
1446,62,Zentel,zentel
1781,81,allegra d 24 hour,allegra d 24 hour
1782,81,Allegra D,allegra d
1783,81,Allegra d-12 hour,allegra d-12 hour
1784,81,Allegra-D,allegra-d
1785,81,Allegra-D 12 Hour,allegra-d 12 hour
1786,81,fenadine HCl + Pseudoephedrine HCl,fenadine hcl + pseudoephedrine hcl
2347,101,altoprev,altoprev
2348,101,6-alpha-Methylcompactin,6-alpha-methylcompactin
2349,101,6alpha-Methylcompactin,6alpha-methylcompactin
2350,101,Altocor,altocor
2351,101,Artein,artein
2352,101,Belvas,belvas
2353,101,BRN 3631989,brn 3631989
...,...,...,...
3701,143,Testandrone,testandrone
3702,143,Testex,testex
3703,143,Testiculosterone,testiculosterone
3704,143,Testim,testim
3705,143,Testobase,testobase
3706,143,Testoderm,testoderm
3707,143,Testoderm TTS,testoderm tts
3708,143,Testogel,testogel
3709,143,Testoject-50,testoject-50
3710,143,Testopropon,testopropon
3711,143,Testosteroid,testosteroid
3712,143,Testosteron,testosteron
3713,143,Testosterona,testosterona
3714,143,Testosterona [INN-Spanish],testosterona [inn-spanish]
3715,143,Testosterone,testosterone
3716,143,Testosterone hydrate,testosterone hydrate
3717,143,Testosteronum,testosteronum
3718,143,Testosteronum [INN-Latin],testosteronum [inn-latin]
3719,143,Testostosterone,testostosterone
3720,143,Testoviron,testoviron
3721,143,Testoviron schering,testoviron schering
3722,143,Testoviron T,testoviron t
3723,143,Testrone,testrone
3724,143,Testryl,testryl
3725,143,Tlando,tlando
3726,143,trans-Testosterone,trans-testosterone
3727,143,UNII-3XMK78S47O,unii-3xmk78s47o
3728,143,Virormone,virormone
3729,143,Virosterone,virosterone
3730,143,Vogelxo,vogelxo

In [22]:
df_new_drugs[df_new_drugs.duplicated(['drug_name_lower'])]

,record_no,drug_name,search_string,drug_name_lower,new_in_old_drugs
158,38177,CFTR-GT,cftr-gt,cftr-gt,0
520,8452,adalimumab (INN),adalimumab,adalimumab (inn),1
521,8452,adalimumab (USAN),adalimumab,adalimumab (usan),1
522,26507,adalimumab (INN),adalimumab,adalimumab (inn),1
523,26507,adalimumab (USAN),adalimumab,adalimumab (usan),1
524,25384,adalimumab (INN),adalimumab,adalimumab (inn),1
525,25384,adalimumab (USAN),adalimumab,adalimumab (usan),1
526,21082,adalimumab (INN),adalimumab,adalimumab (inn),1
527,21082,adalimumab (USAN),adalimumab,adalimumab (usan),1
697,33037,bacoside A,bacoside a,bacoside a,0
699,33038,bacoside B,bacoside b,bacoside b,0
761,25116,bevacizumab (pINN),bevacizumab,bevacizumab (pinn),1
762,23095,bevacizumab (pINN),bevacizumab,bevacizumab (pinn),1
763,25229,bevacizumab (pINN),bevacizumab,bevacizumab (pinn),1
764,28093,bevacizumab (pINN),bevacizumab,bevacizumab (pinn),1
765,22667,bevacizumab (pINN),bevacizumab,bevacizumab (pinn),1
766,25197,bevacizumab (pINN),bevacizumab,bevacizumab (pinn),1
946,4590,darbepoetin alfa (pINN),darbepoetin alfa,darbepoetin alfa (pinn),1
947,3819,darbepoetin alfa (pINN),darbepoetin alfa,darbepoetin alfa (pinn),1
1085,20963,elpamotide (pINN),elpamotide,elpamotide (pinn),0
1166,38416,fenretinide (INN),fenretinide,fenretinide (inn),0
1179,28174,filgrastim (INN),filgrastim,filgrastim (inn),1
1205,12712,fosfomycin (pINN),fosfomycin,fosfomycin (pinn),1
1242,23164,interferon gamma (pINN),interferon gamma,interferon gamma (pinn),0
1308,35495,hydrocodone (INN),hydrocodone,hydrocodone (inn),0
1352,23099,infliximab (INN),infliximab,infliximab (inn),1
1353,23099,infliximab (USAN),infliximab,infliximab (usan),1
1354,23059,infliximab (INN),infliximab,infliximab (inn),1
1355,23059,infliximab (USAN),infliximab,infliximab (usan),1
1356,30345,infliximab (INN),infliximab,infliximab (inn),1
...,...,...,...,...,...
15981,9166,clotrimazole (INN),clotrimazole,clotrimazole (inn),1
16000,20191,mifepristone (INN),mifepristone,mifepristone (inn),1
16002,42211,lidocaine (INN),lidocaine,lidocaine (inn),1
16003,42211,lidocaine (pINN),lidocaine,lidocaine (pinn),1
16007,21162,dexamethasone (INN),dexamethasone,dexamethasone (inn),1
16011,8136,fluconazole (INN),fluconazole,fluconazole (inn),1
16020,1360,icosapent (INN),icosapent,icosapent (inn),0
16021,1360,icosapent ethyl (USAN),icosapent ethyl,icosapent ethyl (usan),0
16027,28083,G-CSF,g-csf,g-csf,0
16028,28083,granulocyte colony stimulating factor,granulocyte colony stimulating factor,granulocyte colony stimulating factor,0
16030,28083,filgrastim (INN),filgrastim,filgrastim (inn),1
16042,40487,epalrestat (pINN),epalrestat,epalrestat (pinn),0
16050,22327,rituximab (INN),rituximab,rituximab (inn),1
16051,22327,rituximab (USAN),rituximab,rituximab (usan),1
16063,29111,CTLA4-Ig,ctla4-ig,ctla4-ig,0
16066,42025,paclitaxel (pINN),paclitaxel,paclitaxel (pinn),1
16077,341,infliximab (INN),infliximab,infliximab (inn),1
16078,341,infliximab (USAN),infliximab,infliximab (usan),1
16081,2888,infliximab (INN),infliximab,infliximab (inn),1
16082,2888,infliximab (USAN),infliximab,infliximab (usan),1
16108,6805,acetylsalicylic acid,acetylsalicylic acid,acetylsalicylic acid,0
16115,39794,loteprednol (INN),loteprednol,loteprednol (inn),0
16116,39794,loteprednol etabonate (USAN),loteprednol etabonate,loteprednol etabonate (usan),1
16156,29132,adalimumab (INN),adalimumab,adalimumab (inn),1
16157,29132,adalimumab (USAN),adalimumab,adalimumab (usan),1
16163,2579,alprostadil (INN),alprostadil,alprostadil (inn),1
16173,15905,octreotide (INN),octreotide,octreotide (inn),0
16174,15905,octreotide acetate (USAN),octreotide acetate,octreotide acetate (usan),0
16175,15905,octreotide hydrochloride (USAN),octreotide hydrochloride,octreotide hydrochloride (usan),0
16193,10197,tacrolimus (INN),tacrolimus,tacrolimus (inn),0

In [ ]:
df_dup_old_drugs.to_excel("../../Data/drugs/_old_drugs_duplicates.xlsx")